name: "Build and Push Shopware Image"
description: "Builds a Shopware Docker image, and optionally pushes it to a Container Registry"
inputs:
  CONTAINER_REGISTRY:
    required: false
    description: "The Docker registry to push the image to"
  PUSH:
    required: false
    description: "Whether to push the image to the registry"
    default: "true"
  CACHE_FROM:
    required: false
    description: "Defines where to pull cached Docker layers from"
  CACHE_TO:
    required: false
    description: "Defines where to push cached Docker layers to"
  TAGS:
    required: false
    description: "Defines the tags to associate with the image"
  DOCKERFILE_PATH:
    required: true
    description: "The path (relative to the project's root) of the Dockerfile used to build image"
  DOCKERFILE_TARGET:
    required: true
    description: "The Docker target to use when building the image"
  IMAGE:
    required: true
    description: "The name of the Docker image to build"
  SHOPWARE_COMPOSER_TOKEN:
    required: true
    description: "The value of your project's Shopware Composer token"

runs:
  using: "composite"
  steps:
    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.DOCKERFILE_PATH }}
        target: ${{ inputs.DOCKERFILE_TARGET }}
        secrets: |
          shopware-composer-token=${{ inputs.SHOPWARE_COMPOSER_TOKEN }}            
        push: ${{ fromJSON(inputs.PUSH) }}
        cache-from: ${{ inputs.CACHE_FROM }}
        cache-to: ${{ inputs.CACHE_TO }}
        tags: ${{ inputs.TAGS }}