name: "Azure Container Apps Deploy Revision"
description: "Deploys a new revision of an Azure Container App"
inputs:
  TENANT:
    required: true
    description: "ID of the Azure tenant to deploy to"
  SUBSCRIPTION:
    required: true
    description: "ID of the Azure subscription to deploy to"
  RESOURCE_GROUP:
    required: true
    description: "Name of the Azure Resource Group to deploy to"
  CONTAINER_REGISTRY:
    required: true
    description: "Name of the Azure Container Registry (fully qualified, e.g. myregistry.azurecr.io)"
  IMAGE:
    required: true
    description: "Name of the Docker image to use when deploying the revision. The github.run_id will be used as the tag."
  CONTAINER_APP:
    required: true
    description: "Name of the Container App to deploy a new revision to"
  MULTI_REVISION:
    required: false
    description: "Whether the Container App is using a multi-revision setup"
    default: "false"
  SERVICE_PRINCIPAL_ID:
    required: true
    description: "The ID of the Service Principal in Azure that will be used to deploy. The Service Principal must have permission to deploy new revisions Container App"
  SERVICE_PRINCIPAL_PASSWORD:
    required: true
    description: "The password for the Service Principal in Azure"

runs:
  using: "composite"
  steps:    
    - name: Log in to Azure
      uses: ./reusable-workflow/.github/actions/azure-login
      with:
        SERVICE_PRINCIPAL_ID: ${{ inputs.SERVICE_PRINCIPAL_ID }}
        SERVICE_PRINCIPAL_PASSWORD: ${{ inputs.SERVICE_PRINCIPAL_PASSWORD }}
        TENANT: ${{ inputs.TENANT }}
        SUBSCRIPTION: ${{ inputs.SUBSCRIPTION }}

    - name: Create new revision of Container App
      uses: azure/cli@v2
      with:
        inlineScript: |
          echo Creating new revision of ${{ inputs.CONTAINER_APP }}...
          retries=0
          while [[ $retries < 3 ]]; do
            az containerapp revision copy \
              --resource-group ${{ inputs.RESOURCE_GROUP }} \
              --name ${{ inputs.CONTAINER_APP }} \
              --image ${{ inputs.CONTAINER_REGISTRY }}/${{ inputs.IMAGE }}:${{ github.run_id }} \
              --revision-suffix run-${{ github.run_id }} \
              || true # do not exit the script on error
            status=$?
            if [[ $status != 0 ]]; then
              echo Revision creation failed, retrying...
              retries=$((retries + 1))
              continue
            else
              exit 0
            fi 
          done
          echo Failed to create revision!

    - name: If using a multi-revision setup, ensure that 100% of traffic is set to the latest...
      uses: azure/cli@v2
      if: inputs.MULTI_REVISION == 'true'
      with:
        inlineScript: |
          echo Ensuring latest revision gets 100% of traffic...
          az containerapp ingress traffic set \
            --resource-group ${{ inputs.RESOURCE_GROUP }} \
            --name ${{ inputs.CONTAINER_APP }} \
            --revision-weight latest=100
