name: "Install workflow tools"
description: "Installs necessary tools for workflows"
runs: 
  using: "composite"
  steps:
    - name: Install jq
      uses: dcarbone/install-jq-action@b7ef57d46ece78760b4019dbc4080a1ba2a40b45
      with:
        version: "1.7"
        force: true