name: "Lint all files"
description: "Lints all files in the repository using predefined linters"
runs: 
  using: "composite"
  steps:
    - name: Lint JSON files
      shell: bash
      run: |
        echo "Linting JSON files..."
        find . -name '*.json' -print0 | xargs -0 -n1 -P4 -I{} bash -c '
          if ! jq empty "{}"; then
            echo "JSON syntax error in {}"
            exit 1
          fi
        '


    # TODO PHP, YAML, XML, Dockerfile linting...