name: "Lint all files"
description: "Lints all files in the repository using predefined linters"
runs: 
  using: "composite"
  steps:
    - name: Lint JSON files
      shell: bash
      run: |
        echo "Linting JSON files..."
        # find + xargs safely handles spaces in filenames
        find . -name '*.json' -print0 | xargs -0 -n1 -P4 -I{} bash -c 'jq empty "{}" || echo "JSON syntax error in {}"'

    # TODO PHP, YAML, XML, Dockerfile linting...