name: "Lint all files"
description: "Lints all files in the repository"
runs: 
  using: "composite"
  steps:
    - name: Lint JSON files
      id: lint-json
      shell: bash
      continue-on-error: true
      run: |
        set -e
        errors=0
        while IFS= read -r -d '' file; do
          if ! output=$(jq empty "$file" 2>&1); then
            echo "JSON syntax error in $file:"
            echo "$output"
            echo "---"
            errors=$((errors+1))
          fi
        done < <(find . -type f -name '*.json' -not -path './.vscode/*' -print0)
        echo "errors=$errors" >> "$GITHUB_OUTPUT"
        if [ "$errors" -ne 0 ]; then
          echo "$errors JSON files found with syntax errors"
        else
          echo "No JSON syntax errors found"
        fi

    - name: Lint PHP files
      id: lint-php
      shell: bash
      continue-on-error: true
      run: |
        set -e
        errors=0
        while IFS= read -r -d '' file; do
          if ! output=$(php -l "$file" 2>&1); then
            echo "PHP syntax error in $file:"
            echo "$output"
            echo "---"
            errors=$((errors+1))
          fi
        done < <(find . -type f -name '*.php' -not -path './vendor/*' -print0)
        echo "errors=$errors" >> "$GITHUB_OUTPUT"
        if [ "$errors" -ne 0 ]; then
          echo "$errors PHP files found with syntax errors"
        else
          echo "No PHP syntax errors found"
        fi

    - name: Lint XML files
      id: lint-xml
      shell: bash
      continue-on-error: true
      run: |
        set -e
        errors=0
        while IFS= read -r -d '' file; do
          if ! output=$(python3 -c "import xml.etree.ElementTree as ET; ET.parse('$file')" 2>&1); then
            echo "XML syntax error in $file:"
            echo "$output"
            echo "---"
            errors=$((errors+1))
          fi
        done < <(find . -type f -name '*.xml' -print0)
        echo "errors=$errors" >> "$GITHUB_OUTPUT"
        if [ "$errors" -ne 0 ]; then
          echo "$errors XML files found with syntax errors"
        else
          echo "No XML syntax errors found"
        fi

    - name: Report linting results
      id: report
      shell: bash
      run: |
        json_errors=${{ steps.lint-json.outputs.errors }}
        php_errors=${{ steps.lint-php.outputs.errors }}
        xml_errors=${{ steps.lint-xml.outputs.errors }}
        total_errors=$((json_errors + php_errors + xml_errors))
        if [ "$total_errors" -ne 0 ]; then
          echo "Linting failed with $total_errors total errors"
          exit 1
        else
          echo "All linting checks passed successfully"
        fi
