name: "Lint all files"
description: "Lints all files in the repository"
runs: 
  using: "composite"
  steps:
    - name: Lint JSON files
      shell: bash
      run: |
        errors=0

        for file in $(find . -name '*.json' -not -path './.vscode/*'); do
          if ! output=$(jq empty "$file" 2>&1); then
            echo "JSON syntax error in $file:"
            echo "$output"
            echo "---"
            errors=$((errors+1))
          fi
        done

        if [ $errors -ne 0 ]; then
          echo "$errors JSON files found with syntax errors"
          exit 1
        else
          echo "No JSON syntax errors found"
        fi

    - name: Lint PHP files
      shell: bash
      run: |
        errors=0

        for file in $(find . -name '*.php' -not -path './vendor/*'); do
          if ! output=$(php -l "$file" 2>&1); then
            echo "PHP syntax error in $file:"
            echo "$output"
            echo "---"
            errors=$((errors+1))
          fi
        done

        if [ $errors -ne 0 ]; then
          echo "$errors PHP files found with syntax errors"
          exit 1
        else
          echo "No PHP syntax errors found"
        fi

    # TODO PHP, YAML, XML, Dockerfile linting...