name: "Copy Azure Container App Config Files"
description: 'Copy in common configuration files required for a Shopware deployment to Container Apps'
inputs:
  CD_PATH:
    required: false
    description: "Location of custom config files in the client's repository"
  SHOPWARE_ROOT:
    required: true
    description: "The path (relative to the project's root) in which the Shopware files are stored (e.g. config, src, etc)"

runs:
  using: "composite"
  steps:
    - name: Copy in config files
      shell: bash
      run: cp -rn ./reusable-workflow/.azure/config/* ${{ inputs.SHOPWARE_ROOT }}/config

    - name: Copy any custom files the client has defined for deployment
      shell: bash
      if: "${{ inputs.CD_PATH != '' }}"
      run: |
        cp -r ${{ inputs.CD_PATH }}/. ${{ inputs.SHOPWARE_ROOT }}