# META - not reusable, runs directly on this repository

name: "CI"

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: "meta-ci-docker-pr-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

jobs:
  meta:
    name: "Meta CI checks on workflows repo"
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Lint files
        uses: ./.github/actions/lint

  skeleton-ci:
    name: "Test CI against skeleton"
    uses: ./.github/workflows/ci-docker.yml
    strategy:
      fail-fast: false
      matrix:
        branch:
          [
            2024.x,
            2025.x,
            2025.x-enterprise,
            2025.x-azure,
            2025.x-enterprise-azure,
            2026.x,
            2026.x-enterprise,
            2026.x-azure,
            2026.x-enterprise-azure,
          ]
    with:
      PROJECT_REPOSITORY: TorqIT/pimcore-skeleton
      PROJECT_REPOSITORY_REF: ${{ matrix.branch }}
      GITHUB_APP_CHECKOUT: true
      RUN_UNIT_TESTS: ${{ matrix.branch != '2024.x' }}
      RUN_PHPSTAN: true
      POST_SCAN_RESULTS_TO_PR: true
      TRIVYIGNORE_PATH: ./.trivyignore.yaml
    secrets:
      GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
      PIMCORE_ENCRYPTION_SECRET: ${{ secrets.PIMCORE_ENCRYPTION_SECRET }}
      PIMCORE_INSTANCE_IDENTIFIER: ${{ secrets.PIMCORE_INSTANCE_IDENTIFIER }}
      PIMCORE_PRODUCT_KEY: ${{ secrets.PIMCORE_PRODUCT_KEY }}
      PIMCORE_ENTERPRISE_TOKEN: ${{ secrets.PIMCORE_ENTERPRISE_TOKEN }}

  skeleton-ci-azure:
    name: "Test Azure CD against skeleton"
    strategy:
      fail-fast: false
      matrix:
        include:
          - github_environment: 2025.x
            parameters_file: "./.github/ci/azure/parameters.2025.x.json"
            skeleton_ref: 2025.x-azure
            agent_server: false
          - github_environment: 2025.x-enterprise
            parameters_file: "./.github/ci/azure/parameters.2025.x-enterprise.json"
            skeleton_ref: 2025.x-enterprise-azure
            agent_server: true
          - github_environment: 2026.x
            parameters_file: "./.github/ci/azure/parameters.2026.x.json"
            skeleton_ref: 2026.x-azure
            agent_server: false
          - github_environment: 2026.x-enterprise
            parameters_file: "./.github/ci/azure/parameters.2026.x-enterprise.json"
            skeleton_ref: 2026.x-enterprise-azure
            agent_server: true
    uses: ./.github/workflows/meta-ci-azure.yml
    with:
      ENVIRONMENT: ${{ matrix.github_environment }}
      PARAMETERS_FILE: ${{ matrix.parameters_file }}
      PROJECT_REPOSITORY_REF: ${{ matrix.skeleton_ref }}
      AGENT_SERVER: ${{ matrix.agent_server }}
    secrets:
      PIMCORE_ENCRYPTION_SECRET: ${{ secrets.PIMCORE_ENCRYPTION_SECRET }}
      PIMCORE_INSTANCE_IDENTIFIER: ${{ secrets.PIMCORE_INSTANCE_IDENTIFIER }}
      PIMCORE_PRODUCT_KEY: ${{ secrets.PIMCORE_PRODUCT_KEY }}
      PIMCORE_ENTERPRISE_TOKEN: ${{ secrets.PIMCORE_ENTERPRISE_TOKEN }}
      AGENT_SERVER_ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      AGENT_SERVER_OPEN_AI_AUTH_TOKEN: ${{ secrets.OPEN_AI_AUTH_TOKEN }}
      CI_SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.CI_SERVICE_PRINCIPAL_PASSWORD }}
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}

  # TODO test CD to VM
