name: CI Azure

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
        description: "The GitHub Environment to provision and deploy to"
      PARAMETERS_FILE:
        required: true
        type: string
        description: "Path to the Azure parameters file used when provisioning the environment"
      PROJECT_REPOSITORY_REF:
        required: false
        type: string
        default: ${{ github.ref }}
        description: "The branch/tag of TorqIT/shopware-skeleton to test against"

    secrets:
      SHOPWARE_COMPOSER_TOKEN:
        required: false
      CI_SERVICE_PRINCIPAL_PASSWORD:
        required: true
      GH_APP_ID:
        required: false
      GH_APP_PRIVATE_KEY:
        required: false

jobs:
  provision:
    name: "Provision Azure environment"
    uses: TorqIT/shopware-azure-provisioning/.github/workflows/provision-azure-environment.yml@upstream-merge-202608
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      PARAMETERS_FILE: ${{ inputs.PARAMETERS_FILE }}
      SERVICE_PRINCIPAL_ID: ${{ vars.CI_SERVICE_PRINCIPAL_ID }}
      SKIP_IF_EXISTS: false
      IMAGE_TAG: upstream-merge-202608
    secrets:
      SHOPWARE_COMPOSER_TOKEN: ${{ secrets.SHOPWARE_COMPOSER_TOKEN }}
      SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.CI_SERVICE_PRINCIPAL_PASSWORD }}

  deploy:
    name: "Test Azure CD workflow against Shopware skeleton"
    needs: provision
    uses: ./.github/workflows/deploy-to-azure-container-apps.yml
    with:
      PROJECT_REPOSITORY: TorqIT/shopware-skeleton
      PROJECT_REPOSITORY_REF: ${{ inputs.PROJECT_REPOSITORY_REF }}
      GITHUB_APP_CHECKOUT: true
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      FEATURE_FLAG_INSTALL_MISSING_BUNDLES: true
      SHOPWARE_ROOT: src
      AZURE_IMAGE_TAG: upstream-merge-202608
    secrets:
      GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
      SHOPWARE_COMPOSER_TOKEN: ${{ secrets.SHOPWARE_COMPOSER_TOKEN }}
      SERVICE_PRINCIPAL_ID: ${{ vars.CI_SERVICE_PRINCIPAL_ID }}
      SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.CI_SERVICE_PRINCIPAL_PASSWORD }}

  post-url:
    name: Post Container App URL to PR
    needs: [deploy]
    uses: TorqIT/shopware-azure-provisioning/.github/workflows/post-container-app-url-to-pr.yml@upstream-merge-202608
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      PARAMETERS_FILE: ${{ inputs.PARAMETERS_FILE }}
      SERVICE_PRINCIPAL_ID: ${{ vars.CI_SERVICE_PRINCIPAL_ID }}
      IMAGE_TAG: upstream-merge-202608
    secrets:
      SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.CI_SERVICE_PRINCIPAL_PASSWORD }}
      SHOPWARE_COMPOSER_TOKEN: ${{ secrets.SHOPWARE_COMPOSER_TOKEN }}
