name: CI Azure

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
        description: "The GitHub Environment to provision and deploy to"
      PARAMETERS_FILE:
        required: true
        type: string
        description: "Path to the Azure parameters file used when provisioning the environment"
      PROJECT_REPOSITORY_REF:
        required: false
        type: string
        default: ${{ github.ref }}
        description: "The branch/tag of TorqIT/pimcore-skeleton to test against"

    secrets:
      PIMCORE_ENCRYPTION_SECRET:
        required: false
      PIMCORE_INSTANCE_IDENTIFIER:
        required: false
      PIMCORE_PRODUCT_KEY:
        required: false
      CI_SERVICE_PRINCIPAL_PASSWORD:
        required: true
      GH_APP_ID:
        required: false
      GH_APP_PRIVATE_KEY:
        required: false

jobs:
  provision:
    name: "Provision Azure environment"
    uses: TorqIT/pimcore-azure-provisioning/.github/workflows/provision-azure-environment.yml@v2
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      PARAMETERS_FILE: ${{ inputs.PARAMETERS_FILE }}
      SERVICE_PRINCIPAL_ID: ${{ vars.CI_SERVICE_PRINCIPAL_ID }}
      SKIP_IF_EXISTS: false
    secrets:
      PIMCORE_ENCRYPTION_SECRET: ${{ secrets.PIMCORE_ENCRYPTION_SECRET }}
      PIMCORE_INSTANCE_IDENTIFIER: ${{ secrets.PIMCORE_INSTANCE_IDENTIFIER }}
      PIMCORE_PRODUCT_KEY: ${{ secrets.PIMCORE_PRODUCT_KEY }}
      SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.CI_SERVICE_PRINCIPAL_PASSWORD }}

  deploy:
    name: "Test Azure CD workflow against Pimcore skeleton"
    needs: provision
    uses: ./.github/workflows/deploy-to-azure-container-apps.yml
    with:
      PROJECT_REPOSITORY: TorqIT/pimcore-skeleton
      PROJECT_REPOSITORY_REF: ${{ inputs.PROJECT_REPOSITORY_REF }}
      GITHUB_APP_CHECKOUT: true
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      FEATURE_FLAG_INSTALL_MISSING_BUNDLES: true
    secrets:
      GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
      PIMCORE_ENCRYPTION_SECRET: ${{ secrets.PIMCORE_ENCRYPTION_SECRET }}
      PIMCORE_INSTANCE_IDENTIFIER: ${{ secrets.PIMCORE_INSTANCE_IDENTIFIER }}
      PIMCORE_PRODUCT_KEY: ${{ secrets.PIMCORE_PRODUCT_KEY }}
      SERVICE_PRINCIPAL_ID: ${{ vars.CI_SERVICE_PRINCIPAL_ID }}
      SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.CI_SERVICE_PRINCIPAL_PASSWORD }}

  post-url:
    name: Post Container App URL to PR
    needs: [deploy]
    uses: TorqIT/pimcore-azure-provisioning/.github/workflows/post-container-app-url-to-pr.yml@v2
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      PARAMETERS_FILE: ${{ inputs.PARAMETERS_FILE }}
      SERVICE_PRINCIPAL_ID: ${{ vars.CI_SERVICE_PRINCIPAL_ID }}
    secrets:
      SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.CI_SERVICE_PRINCIPAL_PASSWORD }}
      PIMCORE_ENCRYPTION_SECRET: ${{ secrets.PIMCORE_ENCRYPTION_SECRET }}
      PIMCORE_PRODUCT_KEY: ${{ secrets.PIMCORE_PRODUCT_KEY }}
      PIMCORE_INSTANCE_IDENTIFIER: ${{ secrets.PIMCORE_INSTANCE_IDENTIFIER }}
