name: Tear down Azure resources for CI

on:
  # Tear down Azure resources every midnight, and also when a PR is closed
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    types: closed

concurrency:
  group: ${{ github.repository }}__${{ github.ref }}-ci-tear-down
  cancel-in-progress: true

jobs:
  tear-down-azure-resources:
    name: Tear down CI Azure resources
    strategy:
      matrix:
        include:
          - parameters-file: "./.github/ci/parameters.2025.x.json"
          - parameters-file: "./.github/ci/parameters.2025.x.json"
    uses: TorqIT/pimcore-azure-provisioning/.github/workflows/tear-down-azure-resources.yml@support-2026.x # TODO changeme back to v2
    with:
      SERVICE_PRINCIPAL_ID: ${{ vars.SERVICE_PRINCIPAL_ID }}
      PARAMETERS_FILE: ${{ matrix.parameters-file }}
    secrets:
      SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
