name: Tear down Azure resources based on a given parameters file

on:
  workflow_call:
    inputs:
      RUNNER:
        required: false
        type: string
        default: ubuntu-24.04
        description: Optional self-hosted runner for this workflow (see https://github.com/TorqIT/shopware-github-actions-workflows#self-hosted-runners)
      SERVICE_PRINCIPAL_ID:
        required: true
        type: string
        description: "Azure Service Principal ID with permissions to deploy resources to the target subscription and resource group"
      PARAMETERS_FILE:
        required: true
        type: string
        description: "Path to the parameters file containing the necessary parameters for provisioning the Azure environment"
      BUILD_IMAGE:
        required: false
        type: boolean
        default: false
        description: "Whether to build the Azure Docker image. Defaults to false"
      IMAGE_TAG:
        required: false
        type: string
        description: "The image tag to use - if BUILD_IMAGE is false, this is the tag that will be pulled"
        default: "2"
      FAIL_ON_ERROR:
        required: false
        type: boolean
        default: true
        description: "Whether to fail the workflow if there are errors during the Azure tear-down"
    secrets:
      SERVICE_PRINCIPAL_PASSWORD:
        required: true
        description: "Azure Service Principal password"

concurrency:
  group: ${{ github.repository }}__${{ github.ref }}-${{ inputs.PARAMETERS_FILE }}-tear-down
  cancel-in-progress: true

jobs:
  tear-down-azure-resources:
    name: Tear down CI Azure resources
    runs-on: ${{ inputs.RUNNER }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Get workflow version
        id: workflow-version
        uses: canonical/get-workflow-version-action@ba22d0abdc1eda539aa3ac81af1cfee160b10714 # v1
        with:
          repository-name: TorqIT/shopware-github-actions-workflows
          file-name: workflow-tear-down-azure-resources.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout workflow repository to use composite actions
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          repository: TorqIT/shopware-github-actions-workflows
          ref: ${{ steps.workflow-version.outputs.sha }}
          path: reusable-workflow
          fetch-depth: 1

      - name: Build and start container, and log in to Azure
        uses: ./reusable-workflow/.github/actions/start-azure-provisioning
        with:
          BUILD_IMAGE: "${{ inputs.BUILD_IMAGE }}"
          SERVICE_PRINCIPAL_ID: ${{ inputs.SERVICE_PRINCIPAL_ID }}
          SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
          PARAMETERS_FILE: ${{ inputs.PARAMETERS_FILE }}
          IMAGE_TAG: ${{ inputs.IMAGE_TAG }}

      - name: Delete Resource Group
        continue-on-error: ${{ !inputs.FAIL_ON_ERROR }}
        run: |
          docker exec azure bash -c '
              az group delete \
                --name $(jq -r ".parameters.resourceGroupName.value" /azure/parameters.json) \
                --yes
          '

      - name: Purge Key Vault
        continue-on-error: ${{ !inputs.FAIL_ON_ERROR }}
        run: |
          docker exec azure bash -c '
              az keyvault purge \
                --name $(jq -r ".parameters.keyVaultName.value" /azure/parameters.json)
          '
